# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  amplify_env:
    description: 'Env used to deploy the stack too'
    required: true
  amplify_command:
    description: 'Command needed for Amplify Deploy'
    required: true
outputs:
  url: # id of output
    description: 'This will be output of the URL for the deployed route'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.amplify_env }}
    - ${{ inputs.amplify_command }}